### ISSUE TITLE
hash constant over several individuals?

### ISSUE THREAD

**Issue by dnil** [squeezeday/udni-tip2toe#1]
Created a handful of phenopackets, and all appear to get the `_hash` of `3449c9e5e332f1dbb81505cd739fbf3f`?
Nice unique `ObjectId` in `_id` of course, but perhaps the hashing is not on the full packet?

**Comment by squeezeday** [comment]
@dnil Bug in phenopacket-api, fixed with https://github.com/squeezeday/phenopacket-api/commit/865ef3b7d934f46370524ed1ab7600caa740f514
